name: ğŸš€ Test Against New Remix Version

on:
  repository_dispatch:
    types: [remix-release]

jobs:
  bump:
    name: ğŸ“¦ Bump Remix Deps
    if: github.repository == 'remix-run/indie-stack'
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - run: |
          git config user.email "hello@remix.run"
          git config user.name "Remix Run Bot"
          git checkout -b remix-release/${{ github.event.client_payload.ref }}

          npm i @remix-run/{node,react,serve,server-runtime}@${{ github.event.client_payload.ref }}
          npm i -D @remix-run/{dev,eslint-config}@${{ github.event.client_payload.ref }}

          git add .
          git commit -m "ğŸš€ bump Remix to v${{ github.event.client_payload.ref }}"
          git push origin remix-release/${{ github.event.client_payload.ref }}

  lint:
    name: â¬£ ESLint
    if: github.repository == 'remix-run/indie-stack'
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3
        with:
          ref: remix-release/${{ github.event.client_payload.ref }}

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: ğŸ”¬ Lint
        run: npm run lint

  typecheck:
    name: Ê¦ TypeScript
    if: github.repository == 'remix-run/indie-stack'
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3
        with:
          ref: remix-release/${{ github.event.client_payload.ref }}

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: ğŸ” Type check
        run: npm run typecheck --if-present

  vitest:
    name: âš¡ Vitest
    if: github.repository == 'remix-run/indie-stack'
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3
        with:
          ref: remix-release/${{ github.event.client_payload.ref }}

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: âš¡ Run vitest
        run: npm run test -- --coverage

  cypress:
    name: âš«ï¸ Cypress
    if: github.repository == 'remix-run/indie-stack'
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3
        with:
          ref: remix-release/${{ github.event.client_payload.ref }}

      - name: ğŸ„ Copy test env vars
        run: cp .env.example .env

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: ğŸ›  Setup Database
        run: npx prisma migrate reset --force

      - name: âš™ï¸ Build
        run: npm run build

      - name: ğŸŒ³ Cypress run
        uses: cypress-io/github-action@v3
        with:
          start: npm run start:mocks
          wait-on: "http://localhost:8811"
        env:
          PORT: "8811"

  cleanup:
    name: ğŸ—‘ Cleanup
    if: always() && github.repository == 'remix-run/indie-stack'
    runs-on: ubuntu-latest
    steps:
      - run: |
          git push origin --delete remix-release/${{ github.event.client_payload.ref }}
